name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
       
      - name: Create 404 page
        run: cp build/index.html build/404.html
      
      # Add the verification step here, after build but before upload
      - name: Verify Assets
        run: |
          echo "Checking _app directory..."
          find build/_app -type f | grep '\.js$' || echo "No JS files found!"
          
          # The curl check won't work during the build since the files aren't deployed yet
          # We'll just check that JS files exist in the build directory
          echo "First few JS files:"
          find build/_app -type f -name "*.js" | head -5
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
