name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: Debug build directory
        run: |
          echo "Contents of build directory:"
          ls -la build
          echo "Contents of build/_app directory:"
          ls -la build/_app || echo "No _app directory found"
      
      - name: Create 404.html
        run: cp build/index.html build/404.html
      
      - name: Add .nojekyll file
        run: touch build/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly specify the token
          commit-message: "Deploy website [skip ci]"  # Add a commit message
          git-config-name: GitHub Actions    # Set the git config name
          git-config-email: actions@github.com  # Set the git config email

      - name: Debug after deploy
        run: |
          echo "Checking remote branches:"
          git fetch
          git branch -r
