name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: Create 404.html
        run: cp build/index.html build/404.html
      
      - name: Add .nojekyll file
        run: touch build/.nojekyll

      - name: Copy public files
        run: |
          mkdir -p build/public
          cp -r public/* build/
      
      # Manual deployment to gh-pages branch
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a new orphan branch
          git checkout --orphan gh-pages
          
          # Remove everything
          git rm -rf .
          
          # Copy build files
          cp -r build/* .
          cp build/.nojekyll .
          
          # Add all files
          git add .
          
          # Commit
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push origin gh-pages --force
          
          echo "Deployed to gh-pages branch"
